require:
  - standard
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive

