module Webex
  class Client
    EXCEPTIONS: Array[Class]

    # Commented this because ruby RBS does not have capability to handle exceptions.
    # def self.query: (
    #     query: String,
    #     variables: Hash[void, void],
    #     operation_name: String,
    #     headers: Hash[String, untyped]
    #   ) -> untyped
  end
end