module Webex
  class Error
    attr_reader code: String
    attr_reader extensions: Hash[String, void]
    attr_reader response: Response
    attr_reader status: Integer
  end

  class ServerError
    def reference_id: () -> String
  end
end
