module Webex
  module Events
    VERSION: String

    class Config
      self.@max_retries: Integer
      self.@open_timeout: Integer
      self.@timeout: Integer
      self.@write_timeout: Integer

      attr_accessor self.access_token: String

      attr_accessor self.logger: Logger

      def self.configure: (Proc) -> void

      def self.max_retries: -> Integer

      def self.max_retries=: (Integer) -> Integer

      def self.open_timeout: -> Integer

      def self.open_timeout=: (Integer) -> Integer

      def self.timeout: -> Integer

      def self.timeout=: (Integer) -> Integer

      def self.write_timeout: -> Integer

      def self.write_timeout=: (Integer) -> Integer
    end
  end
end
