module Webex
  module Events
    VERSION: String

    class Config
      self.@max_retries: Integer

      attr_accessor self.access_token: String

      def self.configure: (Proc) -> void

      def self.max_retries: -> Integer

      def self.max_retries=: (Integer) -> Integer

      def self.ruby_version: -> String
    end
  end
end
