module Webex
  module Events
    VERSION: String

    class Config
      self.@max_retries: Integer

      attr_accessor self.access_token: String

      def self.configure: (Proc) -> void

      def self.max_retries: -> Integer

      def self.max_retries=: (Integer) -> Integer
    end

    def self.assert_access_token!: -> void

    def self.endpoint_url: -> String

    def self.live_token?: -> boolish

    def self.ruby_version: -> String

    def self.sandbox_token?: -> boolish

    def self.user_agent: -> String
  end
end
