module Webex
  module Helpers
    UUID_REGEX_VALIDATOR: ::Regexp

    @introspection_query: String
    @user_agent: String

    def validate_idempotency_key: (String key) -> (untyped | nil | nil)

    def endpoint_url: () -> ("https://public.api.socio.events" | "https://public.sandbox-api.socio.events")

    def live_token?: () -> boolish

    def sandbox_token?: () -> boolish

    def assert_access_token!: () -> untyped

    def ruby_version: () -> string

    def user_agent: () -> ::String

    def introspection_query: -> String
  end
end
