module Webex
  class Request
    CLIENT_ERROR_STATUSES: Range[Integer]
    SERVER_ERROR_STATUSES: Range[Integer]
    UUID_REGEX_VALIDATOR: Regexp

    @options: Hash[String, String]
    @mutex: Mutex
    @query: String
    @variables: Hash[void, void]
    @operation_name: String
    @connection: Faraday::Connection
    @access_token: String

    def self.connection: -> Faraday::Connection

    def self.execute: (query: String, variables: Hash[void, void], operation_name: String, options: Hash[String, untyped]) -> Webex::Response

    def self.url: -> String

    def initialize: (query: String, variables: Hash[void, void], operation_name: String, options: Hash[Symbol, untyped]) -> void

    def execute: () -> Webex::Response

    def validate_idempotency_key: -> void

  end
end