module Webex
  class Request
    ClientErrorStatuses: Range
    ServerErrorStatuses: Range

    @headers: Hash[String, String]
    @mutex: Mutex
    @query: String
    @variables: Hash[void, void]
    @operation_name: String
    @connection: Faraday::Connection
    @access_token: String

    def self.connection: -> Faraday::Connection

    def self.url: -> String

    def initialize: (query: String, variables: Hash[void, void], operation_name: String, headers: Hash[String, String]) -> void

    def execute: () -> Response

  end
end