module Webex
  class Response
    attr_accessor retry_count: Integer
    attr_accessor time_spent_in_ms: Integer
    attr_reader url: String
    attr_reader request_body: String
    attr_reader request_headers: Hash[String, void]
    attr_reader status: Integer
    attr_reader body: Hash[String, void]
    attr_reader headers: Hash[String, void]

    @status: Integer
    @body: Hash[String, void]
    @success: boolish
    @headers: Hash[String, void]

    def success?: -> boolish
  end
end
