name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 2.7
          - 3.0
          - 3.1
          - 3.2
          - head
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
      - name: Run Bundle Commands
        run: |
          bundle config set --with docs
          bundle config set ignore_messages true
          bundle
      - name: Run RuboCop
        run: |
          bundle exec rubocop
      - name: Run tests
        run: |
          bundle exec rspec
    # - name: Publish to RubyGems
    #   run: |
    #     mkdir -p $HOME/.gem
    #     touch $HOME/.gem/credentials
    #     chmod 0600 $HOME/.gem/credentials
    #     printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
    #     gem build *.gemspec
    #     gem push *.gem
    #   env:
    #     GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
