name: CI

on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 2.7
          - 3.0
          - 3.1
          - 3.2
          - head
          - jruby
          - truffleruby
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}
      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev
      - name: Run Bundle Commands
        run: |
          bundle config set --with docs
          bundle config set ignore_messages true
          bundle
      - name: Run RuboCop
        run: |
          bundle exec rubocop
      - name: Run tests with RBS
        if: matrix.version == '2.7' || matrix.version == '3.0' || matrix.version == '3.1' || matrix.version == '3.2' || matrix.version == 'head'
        run: |
          RBS_TEST_TARGET="Webex::*" RUBYOPT="-rrbs/test/setup" bundle exec rspec --force-color
      - name: Run tests without RBS
        if: matrix.version == 'jruby' || matrix.version == 'truffleruby'
        run: |
          bundle exec rspec
